### ISSUE TITLE
Redis: cache session data in redisGraph

### ISSUE THREAD

**Issue by mcorning** [mcorning/lct-c#14]
Currently, index.js caches session data (viz., sessionID, userID, and username).

Why not store these data in the graph?

this would be a nonsignificant refactor, so we better think this through first.

**Comment by MeltedHyperion7** [comment]
I looked at the code for this. The store2 package seems to be intended for use with localStorage/sessionStorage. Is it safe to use it to store data on the server?

Also, it seems that the code reassigns a user ID every time a user logs into a new session. Wouldn't that create multiple user IDs for the same user and mess up the graph?

**Comment by mcorning** [comment]
I have written my own store that goes to nodes fikesystem. I am integrating store into index.js tonight. Hopefully it will be ready for you guys in the morning.

Rwap
^m

________________________________

**Comment by MeltedHyperion7** [comment]
I think it would be better to use something more resilient like mongodb that everyone on the team would be more familiar with.

**Comment by mcorning** [comment]
Mongoose is cool. The store.js file is already isolated from the server code. So if you wrap your mongoose around the same api, nobody will be the wiser (unless they pay attention to the size of node_modules)

Rwap
^m

________________________________

**Comment by mcorning** [comment]
And my little fs hack was mainly so I could get back to work on alerts.

Since I'm about to upgrade my redis subscription I will have more redis databases to use for caching.

Again, those details are abstracted away in index.js.

Rwap
^m

________________________________

**Comment by mcorning** [comment]
Cache class now handles Alerts (alerts.json) and Sessions (sessions.json). I need to checkin blank examples of both data files.
